version: '3'

tasks:
  build-app:
    desc: Build the multicluster-demo application

    cmds:
      - go build ./cmd/multicluster-demo
    generates:
      - multicluster-demo

  run-deploy:
    desc: Deploys a multi-cluster setup in a cloud provider of choice by using Cluster API or CrossPlane according to specification provided in config file

    deps: [build-app]
    cmds:
      - ./multicluster-demo deploy --config .
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    method: checksum

  run-uninstall:
    desc: Uninstalls all project resources

    deps: [build-app]
    cmds:
      - ./multicluster-demo uninstall --config .
    sources:
      - "**/*.go"
      - go.mod
      - go.sum

  test:
    desc: Run all tests in the pkg directory

    cmds:
      - go test -v ./pkg/...

  help:
    desc: Prints help for this applicataion

    cmds:
      - echo "Run 'task -a' for list of available commands"

